// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: resources/internal.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkEvent_Send_FullMethodName = "/NetworkEvent/Send"
)

// NetworkEventClient is the client API for NetworkEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkEventClient interface {
	Send(ctx context.Context, in *UserIpTime, opts ...grpc.CallOption) (*Empty, error)
}

type networkEventClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkEventClient(cc grpc.ClientConnInterface) NetworkEventClient {
	return &networkEventClient{cc}
}

func (c *networkEventClient) Send(ctx context.Context, in *UserIpTime, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NetworkEvent_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkEventServer is the server API for NetworkEvent service.
// All implementations must embed UnimplementedNetworkEventServer
// for forward compatibility.
type NetworkEventServer interface {
	Send(context.Context, *UserIpTime) (*Empty, error)
	mustEmbedUnimplementedNetworkEventServer()
}

// UnimplementedNetworkEventServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkEventServer struct{}

func (UnimplementedNetworkEventServer) Send(context.Context, *UserIpTime) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedNetworkEventServer) mustEmbedUnimplementedNetworkEventServer() {}
func (UnimplementedNetworkEventServer) testEmbeddedByValue()                      {}

// UnsafeNetworkEventServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkEventServer will
// result in compilation errors.
type UnsafeNetworkEventServer interface {
	mustEmbedUnimplementedNetworkEventServer()
}

func RegisterNetworkEventServer(s grpc.ServiceRegistrar, srv NetworkEventServer) {
	// If the following call panics, it indicates UnimplementedNetworkEventServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkEvent_ServiceDesc, srv)
}

func _NetworkEvent_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIpTime)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkEventServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkEvent_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkEventServer).Send(ctx, req.(*UserIpTime))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkEvent_ServiceDesc is the grpc.ServiceDesc for NetworkEvent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkEvent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NetworkEvent",
	HandlerType: (*NetworkEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _NetworkEvent_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resources/internal.proto",
}
