// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: resources/internal.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIpTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Timestamp     int32                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIpTime) Reset() {
	*x = UserIpTime{}
	mi := &file_resources_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIpTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIpTime) ProtoMessage() {}

func (x *UserIpTime) ProtoReflect() protoreflect.Message {
	mi := &file_resources_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIpTime.ProtoReflect.Descriptor instead.
func (*UserIpTime) Descriptor() ([]byte, []int) {
	return file_resources_internal_proto_rawDescGZIP(), []int{0}
}

func (x *UserIpTime) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UserIpTime) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserIpTime) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UserIpTime) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_resources_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_resources_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_resources_internal_proto_rawDescGZIP(), []int{1}
}

var File_resources_internal_proto protoreflect.FileDescriptor

const file_resources_internal_proto_rawDesc = "" +
	"\n" +
	"\x18resources/internal.proto\"b\n" +
	"\n" +
	"UserIpTime\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x05R\ttimestamp\"\a\n" +
	"\x05Empty2-\n" +
	"\fNetworkEvent\x12\x1d\n" +
	"\x04Send\x12\v.UserIpTime\x1a\x06.Empty\"\x00B\x1aZ\x18internal/repository/grpcb\x06proto3"

var (
	file_resources_internal_proto_rawDescOnce sync.Once
	file_resources_internal_proto_rawDescData []byte
)

func file_resources_internal_proto_rawDescGZIP() []byte {
	file_resources_internal_proto_rawDescOnce.Do(func() {
		file_resources_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resources_internal_proto_rawDesc), len(file_resources_internal_proto_rawDesc)))
	})
	return file_resources_internal_proto_rawDescData
}

var file_resources_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resources_internal_proto_goTypes = []any{
	(*UserIpTime)(nil), // 0: UserIpTime
	(*Empty)(nil),      // 1: Empty
}
var file_resources_internal_proto_depIdxs = []int32{
	0, // 0: NetworkEvent.Send:input_type -> UserIpTime
	1, // 1: NetworkEvent.Send:output_type -> Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resources_internal_proto_init() }
func file_resources_internal_proto_init() {
	if File_resources_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resources_internal_proto_rawDesc), len(file_resources_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resources_internal_proto_goTypes,
		DependencyIndexes: file_resources_internal_proto_depIdxs,
		MessageInfos:      file_resources_internal_proto_msgTypes,
	}.Build()
	File_resources_internal_proto = out.File
	file_resources_internal_proto_goTypes = nil
	file_resources_internal_proto_depIdxs = nil
}
